### ISSUE TITLE
Ensure that the cleanup script is available

### ISSUE THREAD

**Issue by denis-yuen** [ICGC-TCGA-PanCancer/pancancer_launcher#6]
This will require the rabbitmqadmin tool to be installed and usable 
https://github.com/CancerCollaboratory/sandbox/blob/develop/pancancer-arch-3/scripts/cleanup.sh

**Comment by SolomonShorser-OICR** [comment]
rabbitmqadmin is already available on the pancancer_launcher, but it needs to be download from http://localhost:15672/cli/rabbitmqadmin to `/usr/local/sbin` (or some similar location). This can be added to the setup process. The script can be easily downloaded.
